output "cluster_name" {
  description = "The name of the EKS cluster"
  value       = module.eks.cluster_name
}

output "cluster_endpoint" {
  description = "The endpoint for the EKS cluster"
  value       = module.eks.cluster_endpoint
}

output "cluster_certificate_authority_data" {
  description = "The certificate authority data for the EKS cluster"
  value       = module.eks.cluster_certificate_authority_data
}


# Output the cluster security group ID for network configuration
output "cluster_security_group_id" {
  description = "Security group ID attached to the EKS cluster"
  value       = module.eks.cluster_security_group_id
}

# Output the kubectl configuration for cluster management
output "kubectl_config" {
  description = "kubectl config as generated by the module"
  value       = module.eks.cluster_endpoint
  sensitive   = true
}

# # Output the IAM role ARN for cluster autoscaler
# output "cluster_autoscaler_iam_role_arn" {
#   description = "IAM role ARN for cluster autoscaler"
#   value       = module.cluster_autoscaler_irsa_role.iam_role_arn
# }
